* Spacemacs Org-mode tutorial


* Table of Contents
 - [[#introduction][Introduction]]
   - [[#summary][Summary]]
   - [[#install][Install]]
 - [[#basic-elements][Basic Elements]]
   - [[#headlines][Headlines]]
   - [[#lists][Lists]]
     - [[#unordered-lists][Unordered lists]]
     - [[#ordered-lists][Ordered lists]]
     - [[#check-lists][Check lists]]
   - [[#links][Links]]
   - [[#images][Images]]
   - [[#tables][Tables]]
 - [[#visibility-cycling][Visibility cycling]]
 - [[#exporting][Exporting]]

* Introduction

** Summary

[[http:orgmode.org][Org]] is a mode for keeping notes, maintaining TODO lists,
and project planning with a fast and effective plain-text
system. This document is intended to teach reader some useful
techniques in org-mode with step-by-step instructions.

** Install

To effectively use org-mode, add this to your =~/.spacemacs= 

#+BEGIN_SRC emacs-lisp
(setq-default dotspacemacs-configuration-layers '(org))
#+END_SRC

* Basic Elements

** Headlines

Headlines define the structure of an outline tree. 
The headlines in Org start with one or more starts. For example:

#+BEGIN_SRC org
* Top level headline
** Second level
*** 3rd level
#+END_SRC

turns to:
* Top level headline
** Second level
*** 3rd level


** Lists

*** Unordered lists

- Unordered lists items start with '-', '+', or '*' as bullets.
- Press 'o' (in vim-mode which create a new line) gives you a new item.
- You might also like nested lists
  - like this one (press 'o' to create new item, press 'ESC' return to normal mode, then '>' to indent it)
- You can also reorder list items using M-arrow('j', 'k')

To create this unorder lists, all you have to do is preface a line with '-':
  
#+BEGIN_SRC org
- Unordered lists items start with '-', '+', or '*' as bullets.
- Press 'o' (in vim-mode which create a new line) gives you a new item.
- You might also like nested lists
  - like this one (press 'o' to create new item, press 'ESC' return to normal mode, then '>' to indent it)
- You can also reorder list items using M-arrow('j', 'k')
#+END_SRC

*** Ordered lists

1. Ordered list items start with a number followed by either '.' or ')', such as '1.' or '1)'
2. Press 'o' (in vim-mode which create a new line) gives you a new item.
3. It's the same rule to create nested lists, and you can also remix two different style lists.
   - To add some additional context.
   - can use this techniques.

To write this in org, you'd do this:
#+BEGIN_SRC org
1. Ordered list items start with a number followed by either '.' or ')', such as '1.' or '1)'
2. Press 'o' (in vim-mode which create a new line) gives you a new item.
3. It's the same rule to create nested lists, and you can also remix two different style lists.
   - To add some additional context.
   - can use this techniques.
#+END_SRC

*** Check lists [/]

- [ ] We can even have check lists
- [ ] Hit M-S-RET gives a new item with a check box
- [ ] You can also have sub items
  - [ ] like this
- [ ] Hit C-c C-c to check/uncheck a box
- [ ] Track the number of items( [finished/total] ) by adding [/] above a checklist

* Links
